### ISSUE TITLE
Luxy is stopping my page transitions with SWUP.js

### ISSUE THREAD

**Issue by Felixr91** [min30327/luxy.js#9]
I'm using Lux with SWUP.js a page transition library with cdn's at in my footer.php file like this... 

```
    <!-- Swup -->
    <script src="https://unpkg.com/swup@latest/dist/swup.min.js"></script>  
    <script type="text/javascript">
        const swup = new Swup();
    </script>
```

```
    <!-- Luxy -->
    <script src="https://cjh.sfo2.cdn.digitaloceanspaces.com/Smooth-Scroll/luxy.js"></script>
    <script type="text/javascript"> 
        luxy.init({
            wrapper: '#luxy',
            wrapperSpeed:  0.08
        });
    </script>
```

For some reason Luxy is stopping my page transitions. I really love both of these libraries and would like to keep both in my project. Any ideas?

**Comment by min30327** [comment]
Hi Felixr91,
Is it the same case as below?

https://github.com/min30327/luxy.js/issues/2#issuecomment-464623971

**Comment by Felixr91** [comment]
I figured it out! Thanks so much!

**Comment by ItayAssouline** [comment]
> I figured it out! Thanks so much!

Can you please explain how? 
Struggling with the same problem

**Comment by haroldao** [comment]
> 

same here @Felixr91 👀
